apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo-app
  labels:
    app: node-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-demo-app
  template:
    metadata:
      labels:
        app: node-demo-app
    spec:
      containers:
        - name: node-demo-app
          image: docker.io/vardawndua/node-demo-app:latest
          ports:
            - containerPort: 3000
